version: "2"
plugins:
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 90
  eslint:
    enabled: false
  fixme:
    enabled: true
checks:
  method-lines:
    config:
      threshold: 30
exclude_patterns:
- documentation_theme/
- test/
- gulpfile.js
- jest/
- node_modules/
