---
engines:
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 90
  eslint:
    enabled: false
  fixme:
    enabled: true
method-lines:
  config:
    threshold: 30
ratings:
  paths:
  - "**.js"
exclude_paths:
- documentation_theme/
- test/
- gulpfile.js
- jest/
- node_modules/
