language: node_js
dist: xenial
cache:
  directories:
    - node_modules
sudo: false
node_js:
  - "10"
before_install:
  - npm install
script:
  - npm run test-no-cov
  - npm test
after_script:
  - codeclimate-test-reporter < coverage/lcov.info
