language: node_js
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
  code_climate:
    repo_token: b2541fd4db954639617d2d7083b5570ba6e2fb1f88875cab12061523287128b6
node_js:
  - "5.6"
before_install:
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then export CXX=g++-4.8; fi
  - $CXX --version
  - npm install
after_script:
  - codeclimate-test-reporter < reports/lcov.info
