language: node_js
sudo: false
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
  code_climate:
    repo_token: b2541fd4db954639617d2d7083b5570ba6e2fb1f88875cab12061523287128b6
node_js:
  - "6.2.1"
before_install:
  - $CXX --version
  - npm install
after_script:
  - codeclimate-test-reporter < reports/lcov.info
