language: node_js
dist: xenial
cache: npm
sudo: false
node_js:
  - "10"
before_install:
  - npm install
script:
  - mkdir coverage
  - npm test
after_script:
  - codeclimate-test-reporter < coverage/lcov.info
